remote_theme: pages-themes/cayman@v0.2.0
plugins:
title: [The History and Operation of Computers ]
description: [A short description of your site's purpose]
google_analytics: [Your Google Analytics tracking ID]
